"""empty message

Revision ID: 485523eacb6a
Revises: 84353da7de62
Create Date: 2018-10-17 13:00:05.083361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485523eacb6a'
down_revision = '84353da7de62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255)))
    op.execute('UPDATE users SET password=email')
    op.alter_column('users', 'password', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
