"""empty message

Revision ID: 84353da7de62
Revises: 
Create Date: 2018-10-17 02:23:07.559846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84353da7de62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
